Repository Nikhil210206/FitYou---Fit_Ai, pull requests merged in 2025-08, with the labels that each got.

#52 UI work is done Issue#3
  templates/Home.html
  templates/Untitled-2.css
  templates/sports.html
Labels: 2 Star

#40 Fix: MongoDB default database check to prevent NotImplementedError
  app.py
Labels: OSCI' 25, 2 Star

#35 Added security
  SECURITY.md
  templates/Home.html
Labels: OSCI' 25, 1 Star

#34 Enhance the navbar
  templates/Home.html
Labels: OSCI' 25, 2 Star

#33 Expanded the diet and exercise dataset and improved the ui of homepag…
  .gitignore
  app.py
  exercises.csv
  templates/Home.html
  templates/diet_data.csv
  templates/fitai.jpg
  templates/logo.jpg
Labels: OSCI' 25, 2 Star

#159 added common favicon
  static/images/faviconn.png
  templates/FY.png
  templates/Home.html
  templates/Sections.html
  templates/Yoga.html
  templates/chatbot.html
  templates/diet.html
  templates/index.html
  templates/sports.html
Labels: enhancement, OSCI' 25, 2 Star

#160 Fix/fityou 151 verified plan contrast
  app.py
  templates/day5.html
  templates/day6.html
  templates/workout_plan.html
Labels: enhancement, OSCI' 25, 2 Star

#172 Redesign Footer In Home Page
  templates/Home.html
Labels: OSCI' 25, 2 Star
